[platformio]
src_dir = main

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

lib_deps =
    sparkfun/SparkFun MAX3010x Pulse and Proximity Sensor Library
    electroniccats/MPU6050

monitor_speed = 115200
upload_speed = 921600
